spring:
  redis:
    host: 192.168.163.3
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  datasource:
    url: jdbc:mysql://192.168.163.3:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 3100880856
    driver-class-name: com.mysql.cj.jdbc.Driver

  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level){yellow} %clr(%logger{15}){cyan} - %msg%n'
logging:
  level:
    com.song: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
